package org.ietf.nea.pa.attribute.enums;


/**
 * Reference IETF RFC 5792 section 4.2:
 * ------------------------------------
 * Number  Integer                  Description
 * ------  -------                  -----------
 * 0       Testing                  Reserved for use in
 *                                  specification examples,
 *                                  experimentation, and testing.
 *                                  
 * 1       Attribute Request        Contains a list of attribute
 *                                  type values defining the
 *                                  attributes desired from the
 *                                  Posture Collectors.
 *                                  
 * 2       Product Information      Manufacturer and product
 *                                  information for the component.
 *
 * 3       Numeric Version          Numeric version of the
 *                                  component.
 *
 * 4       String Version           String version of the
 *                                  component.
 *
 * 5       Operational Status       Describes whether the component
 *                                  is running on the endpoint.
 *
 * 6       Port Filter              Lists the set of ports (e.g.,
 *                                  TCP port 80 for HTTP) that are
 *                                  allowed or blocked on the
 *                                  endpoint.
 *
 * 7       Installed Packages       List of software packages
 *                                  installed on endpoint that
 *                                  provide the requested
 *                                  component.
 *
 * 8       PA-TNC Error             PA-TNC message or attribute
 *                                  processing error.
 * 
 * 9       Assessment Result        Result of the assessment
 *                                  performed by a Posture
 *                                  Validator.
 *
 * 10      Remediation Instructions Instructions for remediation
 *                                  generated by a Posture
 *                                  Validator.
 *                                  
 * 11      Forwarding Enabled       Indicates whether packet
 *                                  forwarding has been enabled
 *                                  between different interfaces on
 *                                  the endpoint.
 *
 * 12      Factory Default Password Indicates whether the endpoint
 *         Enabled                  has a factory default password
 *                                  enabled.
 *
 */

public enum PaAttributeTypeEnum{

    // IETF
    IETF_PA_TESTING            (0),
    IETF_PA_ATTRIBUTE_REQUEST                      (1),
    IETF_PA_PRODUCT_INFORMATION       (2),
    IETF_PA_NUMERIC_VERSION   (3),
    IETF_PA_STRING_VERSION  (4),
    IETF_PA_OPERATIONAL_STATUS                   (5),
    IETF_PA_PORT_FILTER     (6),
    IETF_PA_INSTALLED_PACKAGES           (7),
    IETF_PA_ERROR (8),
    IETF_PA_ASSESSMENT_RESULT (9),
    IETF_PA_REMEDIATION_INSTRUCTIONS (10),
    IETF_PA_FORWARDING_ENABLED (11),
    IETF_PA_FACTORY_DEFAULT_PW_ENABLED (12),
    
    // RESERVED
    IETF_PA_RESERVED               (0xffffffff);
    
    private long messageType;
    
    private PaAttributeTypeEnum(long messageType){
        this.messageType = messageType;
    }

    public long attributeType(){
        return this.messageType;
    }
    
}
